/*
 * generated by Xtext 2.10.0
 */
package org.parisoft.noop.ui.wizard;

import org.eclipse.ui.dialogs.WizardNewProjectCreationPage;

public class NoopWizardNewProjectCreationPage extends WizardNewProjectCreationPage {

	public NoopWizardNewProjectCreationPage(String pageName) {
		super(pageName);
	}

}
